name: hs-static-bin

on:
  push:

env:
  HASKELL_CABAL_VERSION: '3.16.1.0'
  HASKELL_GHC_VERSION: '9.14.1'
  HASKELL_GIT_REPO_URL: 'https://github.com/MichelBoucey/Spintax'
  HASKELL_CABAL_SUB_PROJECT: 'spintax-cli'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: extractions/setup-just@v4

    - name: Pull the spefified hs-static-bin Docker image
      run: |
        docker pull ghcr.io/michelboucey/hs-static-bin:ghc-$HASKELL_GHC_VERSION
        docker image tag \
        ghcr.io/michelboucey/hs-static-bin:ghc-$HASKELL_GHC_VERSION \
        hs-static-bin:ghc-$HASKELL_GHC_VERSION

    - name: Build Haskell binary artifact for the given Haskell Git repo 
      run: just build
